// apps/indusk-admin/src/components/ui/FullscreenDiagram.tsx
"use client";

import { Maximize2, Minus, Plus, RotateCcw, X } from "lucide-react";
import createPanZoom, { type PanZoom } from "panzoom";
import { type ReactNode, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";

export interface FullscreenDiagramProps {
  children: ReactNode;
}

const MIN_ZOOM = 0.05;
const MAX_ZOOM = 10;

/**
 * Wraps a rendered diagram with an expand button that opens a fullscreen
 * modal with pan/zoom. React port of the docs site's Vue component
 * (`apps/docs/src/.vitepress/components/FullscreenDiagram.vue`) — same
 * `panzoom` library, same UX: plain wheel pans, Cmd/Ctrl+wheel zooms,
 * unbounded panning (a bounded box silently blocks panning once the
 * diagram roughly fills the modal — Figma/Miro convention is unbounded).
 *
 * The inline diagram is always rendered (so Mermaid only draws once); on
 * expand, its current innerHTML is cloned into the modal and panzoom
 * attaches to the cloned SVG. Portal to `document.body` mirrors Vue's
 * `<Teleport to="body">` — keeps the modal out of any clipping/overflow
 * ancestor in the plan detail layout.
 */
export function FullscreenDiagram({ children }: FullscreenDiagramProps) {
  const [expanded, setExpanded] = useState(false);
  const [diagramHtml, setDiagramHtml] = useState("");
  const [zoomPct, setZoomPct] = useState(100);
  const inlineRef = useRef<HTMLDivElement>(null);
  const expandedRef = useRef<HTMLDivElement>(null);
  const panzoomRef = useRef<PanZoom | null>(null);

  const toggle = () => {
    if (!expanded) setDiagramHtml(inlineRef.current?.innerHTML ?? "");
    setExpanded((e) => !e);
  };

  useEffect(() => {
    if (!expanded) return;
    document.body.style.overflow = "hidden";

    const svgElement = expandedRef.current?.querySelector("svg");
    let instance: PanZoom | null = null;
    if (svgElement) {
      instance = createPanZoom(svgElement, {
        bounds: false,
        minZoom: MIN_ZOOM,
        maxZoom: MAX_ZOOM,
        beforeWheel(e) {
          if (e.ctrlKey || e.metaKey) return false; // let panzoom zoom
          e.preventDefault();
          instance?.moveBy(-e.deltaX, -e.deltaY, false);
          return true; // plain wheel pans instead of panzoom's default zoom
        },
      });
      panzoomRef.current = instance;
      instance.on("zoom", () => {
        setZoomPct(
          Math.round((panzoomRef.current?.getTransform().scale ?? 1) * 100),
        );
      });
    }

    return () => {
      document.body.style.overflow = "";
      instance?.dispose();
      panzoomRef.current = null;
      setZoomPct(100);
    };
  }, [expanded]);

  const zoomIn = () => {
    const inst = panzoomRef.current;
    if (inst && inst.getTransform().scale < MAX_ZOOM)
      inst.smoothZoom(0, 0, 1.1);
  };
  const zoomOut = () => {
    const inst = panzoomRef.current;
    if (inst && inst.getTransform().scale > MIN_ZOOM)
      inst.smoothZoom(0, 0, 0.9);
  };
  const resetZoom = () => {
    panzoomRef.current?.zoomAbs(0, 0, 1);
    panzoomRef.current?.moveTo(0, 0);
  };

  return (
    <div className="relative w-full" data-testid="fullscreen-diagram">
      <div
        ref={inlineRef}
        className="rounded-lg border border-gray-200 bg-gray-50 p-4"
      >
        {children}
      </div>
      <button
        type="button"
        onClick={toggle}
        title="Expand"
        aria-label="Expand diagram"
        className="absolute right-2 top-2 rounded border border-gray-200 bg-white p-1.5 text-gray-600 opacity-90 hover:bg-gray-50 hover:opacity-100"
      >
        <Maximize2 className="h-4 w-4" aria-hidden />
      </button>

      {expanded &&
        createPortal(
          <div className="fixed inset-0 z-1000 flex items-center justify-center bg-black/85">
            <div className="relative flex h-[95vh] w-[95vw] flex-col rounded-lg bg-white p-6">
              <div className="flex flex-1 items-center justify-center overflow-hidden">
                <div
                  ref={expandedRef}
                  className="cursor-move [&_svg]:block [&_svg]:h-auto [&_svg]:max-h-[90%] [&_svg]:min-w-[600px] [&_svg]:max-w-[90%]"
                  // biome-ignore lint/security/noDangerouslySetInnerHtml: cloning our own already-rendered Mermaid SVG, not user-supplied HTML.
                  dangerouslySetInnerHTML={{ __html: diagramHtml }}
                />
              </div>
              <div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-lg border border-gray-200 bg-white p-2">
                <button
                  type="button"
                  onClick={zoomOut}
                  disabled={zoomPct <= MIN_ZOOM * 100}
                  title="Zoom Out"
                  aria-label="Zoom out"
                  className="rounded p-1 text-gray-600 hover:bg-gray-100 disabled:opacity-30"
                >
                  <Minus className="h-4 w-4" aria-hidden />
                </button>
                <span
                  className="min-w-16 text-center text-sm text-gray-500"
                  data-testid="zoom-level"
                >
                  {zoomPct}%
                </span>
                <button
                  type="button"
                  onClick={zoomIn}
                  disabled={zoomPct >= MAX_ZOOM * 100}
                  title="Zoom In"
                  aria-label="Zoom in"
                  className="rounded p-1 text-gray-600 hover:bg-gray-100 disabled:opacity-30"
                >
                  <Plus className="h-4 w-4" aria-hidden />
                </button>
                <button
                  type="button"
                  onClick={resetZoom}
                  title="Reset Zoom"
                  aria-label="Reset zoom"
                  className="rounded p-1 text-gray-600 hover:bg-gray-100"
                >
                  <RotateCcw className="h-4 w-4" aria-hidden />
                </button>
              </div>
              <button
                type="button"
                onClick={toggle}
                title="Close"
                aria-label="Close"
                className="absolute right-4 top-4 rounded border border-gray-200 bg-white p-1.5 text-gray-600 hover:bg-gray-50"
              >
                <X className="h-4 w-4" aria-hidden />
              </button>
            </div>
          </div>,
          document.body,
        )}
    </div>
  );
}

// apps/indusk-docs/src/.vitepress/components/FullscreenDiagram.vue
<template>
  <div class="diagram-container">
    <div class="diagram" ref="diagramRef">
      <slot></slot>
    </div>
    <button class="expand-btn" @click="toggleExpand" :title="isExpanded ? 'Close' : 'Expand'">
      <svg v-if="!isExpanded" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <path fill="currentColor" d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z"/>
      </svg>
      <svg v-else xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <path fill="currentColor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
      </svg>
    </button>

    <Teleport to="body">
      <div v-if="isExpanded" class="modal-overlay" @click.self="toggleExpand">
        <div class="modal-content">
          <div class="expanded-diagram">
            <div ref="expandedDiagramRef" v-html="diagramHTML"></div>
          </div>
          <div class="zoom-controls">
            <button @click="zoomOut" :disabled="zoom <= 0.05" title="Zoom Out">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentColor" d="M19 13H5v-2h14v2z"/>
              </svg>
            </button>
            <span class="zoom-level">{{ Math.round(zoom * 100) }}%</span>
            <button @click="zoomIn" :disabled="zoom >= 3" title="Zoom In">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentColor" d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/>
              </svg>
            </button>
            <button @click="resetZoom" title="Reset Zoom">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentColor" d="M12 5V1L7 6l5 5V7c3.31 0 6 2.69 6 6s-2.69 6-6 6-6-2.69-6-6H4c0 4.42 3.58 8 8 8s8-3.58 8-8-3.58-8-8-8z"/>
              </svg>
            </button>
          </div>
          <button class="close-btn" @click="toggleExpand">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
              <path fill="currentColor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
            </svg>
          </button>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script setup>
import panzoom from "panzoom";
import { nextTick, ref, watch } from "vue";

const isExpanded = ref(false);
const diagramRef = ref(null);
const expandedDiagramRef = ref(null);
const zoom = ref(1);
const panzoomInstance = ref(null);
const diagramHTML = ref("");

const cloneDiagram = () => {
	if (!diagramRef.value) return;
	diagramHTML.value = diagramRef.value.innerHTML;
};

const toggleExpand = () => {
	if (!isExpanded.value) {
		cloneDiagram();
	}
	isExpanded.value = !isExpanded.value;
	if (isExpanded.value) {
		document.body.style.overflow = "hidden";
		nextTick(() => {
			if (expandedDiagramRef.value) {
				const svgElement =
					expandedDiagramRef.value.querySelector("svg") || expandedDiagramRef.value.firstChild;
				if (svgElement) {
					panzoomInstance.value = panzoom(svgElement, {
						bounds: true,
						boundsPadding: 0.1,
						minZoom: 0.05,
						maxZoom: 10,
					});
					panzoomInstance.value.on("zoom", () => {
						zoom.value = panzoomInstance.value.getTransform().scale;
					});
				}
			}
		});
	} else {
		document.body.style.overflow = "";
		if (panzoomInstance.value) {
			panzoomInstance.value.dispose();
			panzoomInstance.value = null;
		}
		resetZoom();
	}
};

const zoomIn = () => {
	if (panzoomInstance.value) {
		const currentZoom = panzoomInstance.value.getTransform().scale;
		if (currentZoom < 10) {
			panzoomInstance.value.smoothZoom(0, 0, 1.1);
		}
	}
};

const zoomOut = () => {
	if (panzoomInstance.value) {
		const currentZoom = panzoomInstance.value.getTransform().scale;
		if (currentZoom > 0.05) {
			panzoomInstance.value.smoothZoom(0, 0, 0.9);
		}
	}
};

const resetZoom = () => {
	if (panzoomInstance.value) {
		panzoomInstance.value.zoomAbs(0, 0, 1);
		panzoomInstance.value.moveTo(0, 0);
	}
};

watch(isExpanded, (newValue) => {
	if (!newValue) {
		resetZoom();
	}
});
</script>

<style scoped>
.diagram-container {
  position: relative;
  width: 100%;
}

.diagram {
  width: 100%;
  padding: 1rem;
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg-soft);
}

.expand-btn {
  position: absolute;
  top: 1rem;
  right: 1rem;
  background: var(--vp-c-bg);
  border: 1px solid var(--vp-c-divider);
  border-radius: 4px;
  padding: 8px;
  cursor: pointer;
  opacity: 0.9;
  transition: opacity 0.2s;
  z-index: 10;
  color: var(--vp-c-text-1);
}

.expand-btn:hover {
  opacity: 1;
  background: var(--vp-c-bg-soft);
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.85);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal-content {
  position: relative;
  background: var(--vp-c-bg);
  padding: 2rem;
  border-radius: 8px;
  width: 95vw;
  height: 95vh;
  display: flex;
  flex-direction: column;
}

.expanded-diagram {
  flex: 1;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}

.expanded-diagram > div {
  cursor: move;
}

.expanded-diagram :deep(svg) {
  display: block;
  width: auto;
  height: auto;
  min-width: 1000px;
  max-width: 90%;
  max-height: 90%;
  margin: auto;
}

.expanded-diagram :deep(.mermaid) {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
}

.zoom-controls {
  position: absolute;
  bottom: 1rem;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 0.5rem;
  background: var(--vp-c-bg);
  padding: 0.5rem;
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
}

.zoom-controls button {
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-divider);
  border-radius: 4px;
  padding: 4px;
  cursor: pointer;
  opacity: 0.7;
  transition: opacity 0.2s;
  color: var(--vp-c-text-1);
}

.zoom-controls button:hover {
  opacity: 1;
}

.zoom-controls button:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.zoom-level {
  min-width: 4rem;
  text-align: center;
  font-size: 0.9rem;
  color: var(--vp-c-text-2);
}

.close-btn {
  position: absolute;
  top: 1rem;
  right: 1rem;
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-divider);
  border-radius: 4px;
  padding: 8px;
  cursor: pointer;
  opacity: 0.7;
  transition: opacity 0.2s;
  z-index: 10;
  color: var(--vp-c-text-1);
}

.close-btn:hover {
  opacity: 1;
}
</style>
